services:
  api:
    build: .
    command: bash -c "./wait-for-it.sh db:5432 && python src/manage.py migrate && python src/manage.py runserver 0.0.0.0:8080"
    hostname: api01
    ports:
      - "8080:8080"
    volumes:
      - ./src:/src
    environment:
      - DATABASE_URL=postgresql://postgresql:postgresql@123456@db:5432/rinha_backend
      - DB_USERNAME=postgresql
      - DB_SECRET=postgresql@123456
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=rinha_backend
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

  db:
    image: postgres:16.1-alpine3.19
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=api123456
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "340MB"

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
    name: rinhabackend
